name: Practicing Self Hosted Runners

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create a runner file
        run: echo "Creating a text file from self-hosted runner" >> test_runner.txt

      - name: Show path
        run: pwd
  
